name: Update Cat Mood for README

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight to update the state for the week
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Read current date and update mood
      run: |
        import datetime
        import os
        
        current_date = datetime.datetime.now()
        current_month = current_date.month
        current_weekday = current_date.weekday()
        
        if current_weekday == 5 or current_weekday == 6:  # Weekend
            cat_file = 'weekend_cat.txt'
        elif current_month in [12, 1, 2]:  # Winter months
            cat_file = 'winter_cat.txt'
        elif current_month in [3, 4, 5]:  # Spring months
            cat_file = 'spring_cat.txt'
        elif current_date.hour < 8:  # Sleepy mood before 8 AM
            cat_file = 'sleepy_cat.txt'
        else:
            cat_file = 'active_cat.txt'  # Default to active cat
            
        # Read the selected cat file
        with open(f'./pet_states/{cat_file}', 'r') as file:
            cat_art = file.read()
        
        # Write it to the README
        readme_path = './README.md'
        with open(readme_path, 'r') as file:
            readme_content = file.read()
        
        # Update the README with the selected cat art in code block format
        updated_content = readme_content.replace('<!-- CAT_ART -->', f'```bash\n{cat_art}\n```')
        
        with open(readme_path, 'w') as file:
            file.write(updated_content)

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m 'Update cat mood for README'
        git push
