name: Update Profile Pet

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly update on Sunday at midnight
  push:
    branches:
      - main

jobs:
  update-pet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Determine Pet State
        id: set-state
        run: |
          TODAY=$(date +%m)
          if [[ $(git log --since='1 week ago' --pretty=format:'%h' | wc -l) -eq 0 ]]; then
            echo "PET_STATE=sleepy_cat.txt" >> $GITHUB_ENV
          elif [[ "$TODAY" == "12" || "$TODAY" == "01" || "$TODAY" == "02" ]]; then
            echo "PET_STATE=winter_cat.txt" >> $GITHUB_ENV
          elif [[ "$TODAY" == "03" || "$TODAY" == "04" || "$TODAY" == "05" ]]; then
            echo "PET_STATE=spring_cat.txt" >> $GITHUB_ENV
          else
            echo "PET_STATE=active_cat.txt" >> $GITHUB_ENV
          fi

      - name: Update README with Pet (with code block)
        run: |
          PET_ART=$(cat pet_states/$PET_STATE | sed ':a;N;$!ba;s/\n/\\n/g')
          sed -i 's/.*/\n```bash\n'"$PET_ART"'\n```\n/g' README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'bot@example.com'
          git add README.md
          git commit -m "Updated profile pet"
          git push
