name: Update Cat Mood

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for 2 minutes (simulate delay)
        run: |
          echo "Waiting for 2 minutes..."
          sleep 120  # Sleep for 120 seconds (2 minutes)

      - name: Select a random cat mood
        id: cat_mood
        run: |
          moods=("active_cat.txt" "bug_fixer_cat.txt" "celebration_cat.txt" "sleepy_cat.txt" "spring_cat.txt" "weekend_cat.txt" "winter_cat.txt")
          random_mood=${moods[$RANDOM % ${#moods[@]}]}
          echo "SELECTED_MOOD=$(cat pet_states/$random_mood)" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "/## Current Cat Mood/!b;n;c\\${SELECTED_MOOD}" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Update cat mood for the week"
          git push
